export interface IconItem {
  name: string;
  label: string;
}

export const SPORTS_ICONS: IconItem[] = [
  { name: 'sports_soccer', label: 'Fútbol' },
  { name: 'sports_basketball', label: 'Baloncesto' },
  { name: 'sports_volleyball', label: 'Voleibol' },
  { name: 'sports_football', label: 'Fútbol Americano' },
  { name: 'sports_baseball', label: 'Béisbol' },
  { name: 'sports_cricket', label: 'Críquet' },
  { name: 'sports_tennis', label: 'Tenis' },
  { name: 'sports_handball', label: 'Balonmano' },
  { name: 'sports_hockey', label: 'Hockey' },
  { name: 'sports_golf', label: 'Golf' },
  { name: 'pool', label: 'Natación' },
  { name: 'fitness_center', label: 'Gimnasio' },
  { name: 'directions_run', label: 'Atletismo' },
  { name: 'directions_bike', label: 'Ciclismo' },
  { name: 'skateboarding', label: 'Skateboarding' },
  { name: 'snowboarding', label: 'Snowboard' },
  { name: 'surfing', label: 'Surf' },
  { name: 'kayaking', label: 'Kayak' },
  { name: 'sailing', label: 'Vela' },
  { name: 'rowing', label: 'Remo' },
  { name: 'boxing', label: 'Boxeo' },
  { name: 'martial_arts', label: 'Artes Marciales' },
  { name: 'wrestling', label: 'Lucha' },
  { name: 'gymnastics', label: 'Gimnasia' },
  { name: 'badminton', label: 'Bádminton' },
  { name: 'table_tennis', label: 'Tenis de Mesa' },
  { name: 'squash', label: 'Squash' },
  { name: 'racquet', label: 'Ráquetbol' },
  { name: 'bowling', label: 'Bolos' },
  { name: 'curling', label: 'Curling' },
  { name: 'luge', label: 'Luge' },
  { name: 'bobsleigh', label: 'Bobsleigh' },
  { name: 'skiing', label: 'Esquí' },
  { name: 'sailing', label: 'Navegación' },
  { name: 'phishing', label: 'Pesca' },
  { name: 'rock_climbing', label: 'Escalada' },
  { name: 'hiking', label: 'Senderismo' },
  { name: 'camping', label: 'Camping' },
  { name: 'kite_surfing', label: 'Kitesurf' },
  { name: 'windsurfing', label: 'Windsurf' },
  { name: 'scuba_diving', label: 'Buceo' },
  { name: 'snorkeling', label: 'Snorkeling' },
  { name: 'archery', label: 'Tiro con Arco' },
  { name: 'fencing', label: 'Esgrima' },
  { name: 'shooting', label: 'Tiro Deportivo' },
  { name: 'weightlifting', label: 'Halterofilia' },
  { name: 'roller_skating', label: 'Patinaje' },
  { name: 'inline_skating', label: 'Patinaje Inline' },
  { name: 'ice_skating', label: 'Patinaje sobre Hielo' },
  { name: 'motor_sports', label: 'Deportes de Motor' },
  { name: 'sports_motorsports', label: 'Motocross' },
  { name: 'formula_1', label: 'Fórmula 1' },
  { name: 'nascar', label: 'NASCAR' },
  { name: 'rallying', label: 'Rally' },
  { name: 'equestrian', label: 'Equitación' },
  { name: 'polo', label: 'Polo' },
  { name: 'rugby', label: 'Rugby' },
  { name: 'lacrosse', label: 'Lacrosse' },
  { name: 'field_hockey', label: 'Hockey Campo' },
  { name: 'water_polo', label: 'Waterpolo' },
  { name: 'diving', label: 'Salto' },
  { name: 'synchronized_swimming', label: 'Natación Sincronizada' },
  { name: 'triathlon', label: 'Triatlón' },
  { name: 'pentathlon', label: 'Pentatlón' },
  { name: 'decathlon', label: 'Decatlón' },
  { name: 'crossword', label: 'Ajedrez' },
  { name: 'casino', label: 'Apuestas' },
];

export const ICON_NAMES = SPORTS_ICONS.map((icon) => icon.name);

export const ICON_MAP: Record<string, string> = SPORTS_ICONS.reduce(
  (acc, icon) => {
    acc[icon.name] = icon.label;
    return acc;
  },
  {} as Record<string, string>,
);
