export interface IconItem {
  name: string;
  label: string;
}

export const ANIMAL_ICONS: IconItem[] = [
  { name: 'pets', label: 'Mascotas' },
  { name: 'cruelty_free', label: 'Cruelty Free' },
  { name: 'pest_control', label: 'Control de Plagas' },
  { name: 'bug_report', label: 'Reporte de Insecto' },
  { name: 'park', label: 'Parque' },
  { name: 'forest', label: 'Bosque' },
  { name: 'grass', label: 'Hierba' },
  { name: 'nature', label: 'Naturaleza' },
  { name: 'eco', label: 'Ecológico' },
  { name: 'spa', label: 'Spa' },
  { name: 'yard', label: 'Jardín' },
  { name: 'water', label: 'Agua' },
  { name: 'water_drop', label: 'Gota de Agua' },
  { name: 'waves', label: 'Olas' },
  { name: 'waterfall', label: 'Cascada' },
  { name: 'waterfront', label: 'Orilla' },
  { name: 'wb_sunny', label: 'Sol' },
  { name: 'nights_stay', label: 'Noche' },
  { name: 'wb_cloudy', label: 'Nublado' },
  { name: 'cloud', label: 'Nube' },
  { name: 'filter_drama', label: 'Drama' },
  { name: 'thunderstorm', label: 'Tormenta' },
  { name: 'ac_unit', label: 'Nieve' },
  { name: 'beach_access', label: 'Playa' },
  { name: 'castle', label: 'Castillo' },
  { name: 'villa', label: 'Villa' },
  { name: 'house', label: 'Casa' },
  { name: 'home', label: 'Hogar' },
  { name: 'cottage', label: 'Casa de Campo' },
  { name: 'apartment', label: 'Apartamento' },
  { name: 'holiday_village', label: 'Aldea Turística' },
  { name: 'location_city', label: 'Ciudad' },
  { name: 'terrain', label: 'Terreno' },
  { name: 'landscape', label: 'Paisaje' },
  { name: 'photo_camera', label: 'Cámara' },
  { name: 'photo_library', label: 'Galería' },
  { name: 'camera_roll', label: 'Rollo de Cámara' },
  { name: 'image', label: 'Imagen' },
  { name: 'wallpaper', label: 'Fondo de Pantalla' },
  { name: 'filter_vintage', label: 'Filtro Vintage' },
  { name: 'local_florist', label: 'Floristería' },
  { name: 'local_parking', label: 'Estacionamiento' },
  { name: 'directions_car', label: 'Coche' },
  { name: 'directions_walk', label: 'Caminar' },
  { name: 'pedestrian', label: 'Peatón' },
  { name: 'farm', label: 'Granja' },
  { name: 'agriculture', label: 'Agricultura' },
  { name: 'compost', label: 'Composta' },
  { name: 'tractor', label: 'Tractor' },
  { name: 'pest_control_rodent', label: 'Roedores' },
  { name: 'shower', label: 'Ducha' },
  { name: 'bathtub', label: 'Bañera' },
  { name: 'hot_tub', label: 'Jacuzzi' },
  { name: 'room_service', label: 'Servicio de Habitación' },
  { name: 'restaurant', label: 'Restaurante' },
  { name: 'local_cafe', label: 'Cafetería' },
  { name: 'local_bar', label: 'Bar' },
  { name: 'local_dining', label: 'Comida' },
  { name: 'icecream', label: 'Helado' },
  { name: 'cookie', label: 'Galleta' },
  { name: 'candy', label: 'Dulces' },
  { name: 'lunch_dining', label: 'Almuerzo' },
  { name: 'breakfast_dining', label: 'Desayuno' },
  { name: 'dinner_dining', label: 'Cena' },
  { name: 'bakery_dining', label: 'Panadería' },
  { name: 'ramen_dining', label: 'Ramen' },
  { name: 'set_meal', label: 'Comida Preparada' },
  { name: 'local_grocery_store', label: 'Tienda de Abarrotes' },
  { name: 'storefront', label: 'Tienda' },
  { name: 'shopping_bag', label: 'Bolsa de Compras' },
  { name: 'shopping_cart', label: 'Carrito' },
  { name: 'point_of_sale', label: 'Punto de Venta' },
  { name: 'qr_code', label: 'Código QR' },
  { name: 'credit_card', label: 'Tarjeta de Crédito' },
  { name: 'payments', label: 'Pagos' },
  { name: 'account_balance', label: 'Cuenta Bancaria' },
  { name: 'savings', label: 'Ahorros' },
  { name: 'trending_up', label: 'Tendencia' },
  { name: 'show_chart', label: 'Gráfico' },
  { name: 'pie_chart', label: 'Gráfico de Pie' },
  { name: 'bar_chart', label: 'Gráfico de Barras' },
  { name: 'timeline', label: 'Línea de Tiempo' },
  { name: 'calendar_month', label: 'Calendario' },
  { name: 'event', label: 'Evento' },
  { name: 'celebration', label: 'Celebración' },
  { name: 'party_mode', label: 'Modo Fiesta' },
  { name: 'card_giftcard', label: 'Regalo' },
  { name: 'favorite', label: 'Favorito' },
  { name: 'star', label: 'Estrella' },
  { name: 'thumb_up', label: 'Me gusta' },
  { name: 'sentiment_satisfied', label: 'Satisfecho' },
  { name: 'mood', label: 'Estado de Ánimo' },
  { name: 'sentiment_very_satisfied', label: 'Muy Satisfecho' },
  { name: 'sentiment_dissatisfied', label: 'Insatisfecho' },
  { name: 'sentiment_neutral', label: 'Neutral' },
  { name: 'emoji_emotions', label: 'Emociones' },
  { name: 'emoji_events', label: 'Eventos' },
  { name: 'psychology', label: 'Psicología' },
  { name: 'self_improvement', label: 'Automejora' },
  { name: 'accessibility_new', label: 'Accesibilidad' },
  { name: 'accessibility', label: 'Accesible' },
  { name: 'accessible', label: 'Accesible' },
  { name: 'videocam', label: 'Videocámara' },
  { name: 'movie', label: 'Película' },
  { name: 'music_note', label: 'Música' },
  { name: 'headphones', label: 'Auriculares' },
  { name: 'headset', label: 'Auricular' },
  { name: 'speaker', label: 'Altavoz' },
  { name: 'radio', label: 'Radio' },
  { name: 'tv', label: 'Televisión' },
  { name: 'smartphone', label: 'Teléfono' },
  { name: 'laptop', label: 'Laptop' },
  { name: 'computer', label: 'Computadora' },
  { name: 'tablet', label: 'Tableta' },
  { name: 'gamepad', label: 'Control de Juego' },
  { name: 'sports', label: 'Deportes' },
];

export const SPORTS_ICONS: IconItem[] = [
  { name: 'sports_soccer', label: 'Fútbol' },
  { name: 'sports_basketball', label: 'Baloncesto' },
  { name: 'sports_volleyball', label: 'Voleibol' },
  { name: 'sports_football', label: 'Fútbol Americano' },
  { name: 'sports_baseball', label: 'Béisbol' },
  { name: 'sports_cricket', label: 'Críquet' },
  { name: 'sports_tennis', label: 'Tenis' },
  { name: 'sports_handball', label: 'Balonmano' },
  { name: 'sports_hockey', label: 'Hockey' },
  { name: 'sports_golf', label: 'Golf' },
  { name: 'pool', label: 'Natación' },
  { name: 'fitness_center', label: 'Gimnasio' },
  { name: 'directions_run', label: 'Atletismo' },
  { name: 'directions_bike', label: 'Ciclismo' },
  { name: 'skateboarding', label: 'Skateboarding' },
  { name: 'snowboarding', label: 'Snowboard' },
  { name: 'surfing', label: 'Surf' },
  { name: 'kayaking', label: 'Kayak' },
  { name: 'sailing', label: 'Vela' },
  { name: 'rowing', label: 'Remo' },
  { name: 'boxing', label: 'Boxeo' },
  { name: 'martial_arts', label: 'Artes Marciales' },
  { name: 'wrestling', label: 'Lucha' },
  { name: 'gymnastics', label: 'Gimnasia' },
  { name: 'badminton', label: 'Bádminton' },
  { name: 'table_tennis', label: 'Tenis de Mesa' },
  { name: 'squash', label: 'Squash' },
  { name: 'racquet', label: 'Ráquetbol' },
  { name: 'bowling', label: 'Bolos' },
  { name: 'curling', label: 'Curling' },
  { name: 'luge', label: 'Luge' },
  { name: 'bobsleigh', label: 'Bobsleigh' },
  { name: 'skiing', label: 'Esquí' },
  { name: 'sailing', label: 'Navegación' },
  { name: 'phishing', label: 'Pesca' },
  { name: 'rock_climbing', label: 'Escalada' },
  { name: 'hiking', label: 'Senderismo' },
  { name: 'camping', label: 'Camping' },
  { name: 'kite_surfing', label: 'Kitesurf' },
  { name: 'windsurfing', label: 'Windsurf' },
  { name: 'scuba_diving', label: 'Buceo' },
  { name: 'snorkeling', label: 'Snorkeling' },
  { name: 'archery', label: 'Tiro con Arco' },
  { name: 'fencing', label: 'Esgrima' },
  { name: 'shooting', label: 'Tiro Deportivo' },
  { name: 'weightlifting', label: 'Halterofilia' },
  { name: 'roller_skating', label: 'Patinaje' },
  { name: 'inline_skating', label: 'Patinaje Inline' },
  { name: 'ice_skating', label: 'Patinaje sobre Hielo' },
  { name: 'motor_sports', label: 'Deportes de Motor' },
  { name: 'sports_motorsports', label: 'Motocross' },
  { name: 'formula_1', label: 'Fórmula 1' },
  { name: 'nascar', label: 'NASCAR' },
  { name: 'rallying', label: 'Rally' },
  { name: 'equestrian', label: 'Equitación' },
  { name: 'polo', label: 'Polo' },
  { name: 'rugby', label: 'Rugby' },
  { name: 'lacrosse', label: 'Lacrosse' },
  { name: 'field_hockey', label: 'Hockey Campo' },
  { name: 'water_polo', label: 'Waterpolo' },
  { name: 'diving', label: 'Salto' },
  { name: 'synchronized_swimming', label: 'Natación Sincronizada' },
  { name: 'triathlon', label: 'Triatlón' },
  { name: 'pentathlon', label: 'Pentatlón' },
  { name: 'decathlon', label: 'Decatlón' },
  { name: 'crossword', label: 'Ajedrez' },
  { name: 'casino', label: 'Apuestas' },
];

export const ICON_NAMES = SPORTS_ICONS.map((icon) => icon.name);

export const ICON_MAP: Record<string, string> = SPORTS_ICONS.reduce(
  (acc, icon) => {
    acc[icon.name] = icon.label;
    return acc;
  },
  {} as Record<string, string>,
);

export const ANIMAL_ICON_NAMES = ANIMAL_ICONS.map((icon) => icon.name);

export const ANIMAL_ICON_MAP: Record<string, string> = ANIMAL_ICONS.reduce(
  (acc, icon) => {
    acc[icon.name] = icon.label;
    return acc;
  },
  {} as Record<string, string>,
);
